import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import { Excalidraw } from "@excalidraw/excalidraw"
import { useState, useEffect } from "react"
import dynamic from "next/dynamic"


const inter = Inter({ subsets: ['latin'] })
const Drawboard = dynamic(()=>import("../components/drawboard"),{ssr:false})


export default function Home() {

  const [userInput, setUserInput] = useState('')
  const [apiOutput, setApiOutput] = useState('')

  const callGenerateEndpoint = async () => {

    const response = await fetch('/api/generate', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({ userInput }),
    });
  
    const data = await response.json();
    const { output } = data;
  
    setApiOutput(`${output.text}`);
  }
  
    const onUserChangedText = (e) => {
      setUserInput(e.target?.value);
    };

  
  

  return (
    <div>
      <Head>
        <title>Welcome To Algo_Lego</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head> 

      <div>
          <Drawboard text={apiOutput}/>    
      </div>
      
      <div>
      <div className='flex flex-wrap justify-center'>
        <label className="block mb-2 text-xl font-medium text-white font-bold m-5">Your Question?</label>
        <textarea
          className='block p-2.5 text-sm text-gray-900  rounded-lg border border-gray-300 focus:ring-blue-500 focus:border-blue-500 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500 w-2/5 flex-none m-3'
          placeholder="start typing here"
          value={userInput}
          onChange={onUserChangedText}
        />
         <button
        className="bg-indigo-300 px-6 py-2 rounded cursor-pointer m-5"
        onClick={callGenerateEndpoint}>
          Get Answer
        </button>
        </div>


        <div>
        {apiOutput && (
      <div>
        <div>
        </div>
        <div className='flex flex-wrap justify-center'>
        <h3 className='text-white m-5' contentEditable="true">
          {apiOutput}
        </h3>
        </div>
      </div>
      )}    </div>
      </div> 
    </div>
  );
}
